### ISSUE TITLE
tkinter module issue

### ISSUE THREAD

**Issue by Weaita** [tianlang0704/ComfyUI-StableProjectorzBridge#1]
I installed the node in my comfyui and the error _No module named 'tkinter'_ appeared. Apparently the standalone python version that comfyui uses does not include tkinter and it cannot be installed with pip either.
In the end I simply deleted the lines that imported tkinter and that's it, PIL already has a function called Image so tkinter seems unnecessary

P.S: Excellent script, using Projectorz along with ComfyUI is very comfortable :) it would be great to be able to configure the other parameters from Projectorz

**Comment by tianlang0704** [comment]
Oh, thank you for letting me know. The tkinter import was added by mistake. I'll fix it right now.

About using the other parameters from projectorz, later I'll add a node to let you select any of the the parameters sent from projectorz, so you can use it anywhere you want in the graph.

**Comment by tianlang0704** [comment]
Parameter nodes added, let me know if there's any problem.
