### ISSUE TITLE
Problem with launching Stable Projectorz after updating Comfy UI

### ISSUE THREAD

**Issue by StanislavShashkov** [tianlang0704/ComfyUI-StableProjectorzBridge#11]
After updating Comfy UI Stable Projectorz stopped seeing it and the red scale is constantly on, I installed different versions of SPZ but it didn't help what could be the problem? Before the update everything worked, without errors.

**Comment by tianlang0704** [comment]
If the ComfyUI runs fine but SPZ not seeing it, the most probable problem could be the port. 8188 is the defualt port for ComfyUI but sometimes ComfyUI fails to exit and there could be multiple instances with different port number, and some instances do not respond. Maybe try 8189 and see if it fixes the problem?

**Comment by tianlang0704** [comment]
> After updating Comfy UI Stable Projectorz stopped seeing it and the red scale is constantly on, I installed different versions of SPZ but it didn't help what could be the problem? Before the update everything worked, without errors.

I updated to the latest ComfyUI and SPZ, everything works for me. Could you check on the console window of the ComfyUI and see if the node loaded correctly? Or it'll be nice if you can attach a full text log of your ComfyUI startup.

**Comment by tianlang0704** [comment]
> After updating Comfy UI Stable Projectorz stopped seeing it and the red scale is constantly on, I installed different versions of SPZ but it didn't help what could be the problem? Before the update everything worked, without errors.

Someone in SPZ discord server reported similar problem and I've updated the bridge to fix it, please see if it's still not connecting. I'll close this for now, and if it's still having problem, please leave a note and I'll reopen this issue.
