### ISSUE TITLE
Buggy behavior, this blue texture from the projectorz controlnet input

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [tianlang0704/ComfyUI-StableProjectorzBridge#6]
![image](https://github.com/tianlang0704/ComfyUI-StableProjectorzBridge/assets/120438550/db68c30b-0e07-49f3-a661-c95d3e48030e)

**Comment by tianlang0704** [comment]
The blue texture means it didn't find the image sent from Projectorz. 
Since the Projectorz Parameter didn't show any value, the problem might be Projectorz not sending anything.
Please make sure your run is triggered with Projectorz's Gen Art button, and there's no error report in the console.

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/tianlang0704/ComfyUI-StableProjectorzBridge/assets/120438550/99916d94-85f3-4091-a8a2-0e3ca8e505bb)
hi!
some times it works some times it's doesn't 
which workflow I should use?

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/tianlang0704/ComfyUI-StableProjectorzBridge/assets/120438550/b4cbcf0d-91f5-4e5a-85f5-f9fdf46ca322)

**Comment by KillyTheNetTerminal** [comment]
when I try to use the painting mode

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/tianlang0704/ComfyUI-StableProjectorzBridge/assets/120438550/abe40190-02c3-4a8c-9ce5-93727d43422b)

**Comment by KillyTheNetTerminal** [comment]
Traceback (most recent call last):
  File "C:\Users\WarMa\miniconda3\envs\com\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WarMa\miniconda3\envs\com\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WarMa\miniconda3\envs\com\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\server.py", line 43, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\server.py", line 55, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge\apis.py", line 107, in img2img_handler
    await ws.run_prompt(random_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run_prompt() missing 1 required positional argument: 'json_data'
(how can I use inpainting?)

**Comment by tianlang0704** [comment]
It's fixed now. There was a bug with inpaint.
The get progress 404 warning is also fixed.
And I added sample workflow for generating and inpainting in the ReadMe file.
Thanks for letting me know the problem.
Pleaese have a try and see if  it's working.

**Comment by KillyTheNetTerminal** [comment]
Thanks for this very usefull node, it workd better now!

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/tianlang0704/ComfyUI-StableProjectorzBridge/assets/120438550/65f33ea3-ed01-491b-8058-0c7d815ac714)
is used only for inpainting right? there is a wey to switch inside the workflow automatically between generate texture and inpainting modes?

**Comment by tianlang0704** [comment]
1. Yes, Projecctorz Init Input is only used for receiving inpaint base image and mask sent from Projectorz.
2. ControlNet/Inpaint/Inpaint+controlnet are entirely different workflows, so I use workflow manager for quickly switching between them.
There might be some custom nodes for control flow but I don't think ComfyUI is not very good at it, It'll become very complicated very quickly.
You can still try though. :D

**Comment by KillyTheNetTerminal** [comment]
yep I think will be very usefull have a custom node that let you make floating buttoms from comfyui workflows, I mean like floating buttom out of the web browser to change workflow, something like make the mute groups node from https://github.com/rgthree/rgthree-comfy?tab=readme-ov-file#fast-muter but floating on top of other applications
